Feat/use pipenv and makefile
pedrocecchetti/sciapi pull request #3
Opened 2020-08-23 02:39 UTC by yashin5

2020-08-23 12:15 UTC, pedrocecchetti requested changes
Tu chegou a tentar rodar?
No meu a FastAPi nao roda por causa da dependència do **uvicorn**

2020-08-23 12:15 UTC, pedrocecchetti commented on Pipfile
> +fastapi = "*"
Aqui ou precisamos instalar todas as dependencias da fastapi ou o uvicorn pelo menos

`fastapi = {extras = ["all"], version = "*"}`

ou 
`fastapi = "*" ` 
`uvicorn = "*"`

2020-08-27 23:18 UTC, yashin5 commented on Pipfile
> +fastapi = "*"
@pedrocecchetti realmente, acabei esquecendo de adicionar ele no pipfile, mas adicionei aqui e nao to conseguindo fazer rodar, o run.py não reconhece o módulo. to vendo como resolver

2020-08-28 11:14 UTC, pedrocecchetti commented on Dockerfile
> +CMD ["pipenv", "run", "python", "./run.py" ]
Acho que o que estamos fazendo errado tb, é que no processo do build do container, tinhamos que executar as coisas relacionadas ao Pipfile antes. O que teoricamente faz o pipenv run?

2020-12-28 16:35 UTC, closed without merging